In [4]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## New material

In [5]:
full = Table.read_table('nc-est2019-agesex-res.csv')
# the line above is doing a couple of things
# Table creates a new table
# .read_table tells python to read a table from somewhere, 
# that where is in our file path, and the title nc-est2019-agesex-res.csv
# saving this table to the name, full
full

# what does each row represent?
# each row represents the population of a specific age

SEX  | AGE  | CENSUS2010POP | ESTIMATESBASE2010 | POPESTIMATE2010 | POPESTIMATE2011 | POPESTIMATE2012 | POPESTIMATE2013 | POPESTIMATE2014 | POPESTIMATE2015 | POPESTIMATE2016 | POPESTIMATE2017 | POPESTIMATE2018 | POPESTIMATE2019
0    | 0    | 3944153       | 3944160           | 3951430         | 3963092         | 3926570         | 3931258         | 3954787         | 3983981         | 3954773         | 3893990         | 3815343         | 3783052
0    | 1    | 3978070       | 3978090           | 3957730         | 3966225         | 3977549         | 3942698         | 3948891         | 3973133         | 4002903         | 3972711         | 3908830         | 3829599
0    | 2    | 4096929       | 4096939           | 4090621         | 3970654         | 3978925         | 3991740         | 3958711         | 3966321         | 3991349         | 4020045         | 3987032         | 3922044
0    | 3    | 4119040       | 4119051           | 4111688         | 4101644         | 3981531         | 3991017         | 4005928         | 3974351         | 3982984         | 4006946         | 4033038         | 3998665
0    | 4    | 4063170       | 4063186           | 4077346         | 4121488         | 4111490         | 3992502         | 4004032         | 4020292         | 3989750         | 3997280         | 4018719         | 4043323
0    | 5    | 4056858       | 4056872           | 4064521         | 4087054         | 4131049         | 4121876         | 4004576         | 4017589         | 4035033         | 4003452         | 4008443         | 4028281
0    | 6    | 4066381       | 4066412           | 4072904         | 4074531         | 4096631         | 4141126         | 4133372         | 4017388         | 4031568         | 4048018         | 4014057         | 4017227
0    | 7    | 4030579       | 4030594           | 4042990         | 4082821         | 4084175         | 4106756         | 4152666         | 4145872         | 4030888         | 4044139         | 4058370         | 4022319
0    | 8    | 4046486       | 4046497           | 4025501         | 4052773         | 4092559         | 4094513         | 4118349         | 4165033         | 4158848         | 4042924         | 4054236         | 4066194
0    | 9    | 4148353       | 4148369           | 4125312         | 4035319         | 4062726         | 4103052         | 4106068         | 4130887         | 4177895         | 4170813         | 4053179         | 4061874
... (296 rows omitted)

In [8]:
full.sort('AGE')
# Sex = 0, is combination of male and female population for that age
# Sex = 1, male
# Sex = 2, female
# data can be biased, we are looking at binary representations of sex
# we are missing parts of our population that do not subscribe to this binary representation

SEX  | AGE  | CENSUS2010POP | ESTIMATESBASE2010 | POPESTIMATE2010 | POPESTIMATE2011 | POPESTIMATE2012 | POPESTIMATE2013 | POPESTIMATE2014 | POPESTIMATE2015 | POPESTIMATE2016 | POPESTIMATE2017 | POPESTIMATE2018 | POPESTIMATE2019
0    | 0    | 3944153       | 3944160           | 3951430         | 3963092         | 3926570         | 3931258         | 3954787         | 3983981         | 3954773         | 3893990         | 3815343         | 3783052
1    | 0    | 2014276       | 2014278           | 2018474         | 2028430         | 2007742         | 2009723         | 2024511         | 2037646         | 2021375         | 1991761         | 1951663         | 1935117
2    | 0    | 1929877       | 1929882           | 1932956         | 1934662         | 1918828         | 1921535         | 1930276         | 1946335         | 1933398         | 1902229         | 1863680         | 1847935
0    | 1    | 3978070       | 3978090           | 3957730         | 3966225         | 3977549         | 3942698         | 3948891         | 3973133         | 4002903         | 3972711         | 3908830         | 3829599
1    | 1    | 2030853       | 2030861           | 2020235         | 2025272         | 2035213         | 2015723         | 2018511         | 2033686         | 2046917         | 2030158         | 1999022         | 1958585
2    | 1    | 1947217       | 1947229           | 1937495         | 1940953         | 1942336         | 1926975         | 1930380         | 1939447         | 1955986         | 1942553         | 1909808         | 1871014
0    | 2    | 4096929       | 4096939           | 4090621         | 3970654         | 3978925         | 3991740         | 3958711         | 3966321         | 3991349         | 4020045         | 3987032         | 3922044
1    | 2    | 2092198       | 2092202           | 2088545         | 2026392         | 2031333         | 2042266         | 2023752         | 2027455         | 2042821         | 2055454         | 2037249         | 2005544
2    | 2    | 2004731       | 2004737           | 2002076         | 1944262         | 1947592         | 1949474         | 1934959         | 1938866         | 1948528         | 1964591         | 1949783         | 1916500
0    | 3    | 4119040       | 4119051           | 4111688         | 4101644         | 3981531         | 3991017         | 4005928         | 3974351         | 3982984         | 4006946         | 4033038         | 3998665
... (296 rows omitted)

In [9]:
# let's create a new table, called partial and select a few columns to work with
# it makes it easier to manage, since the original table is so large
partial = full.select('SEX', 'AGE', 'POPESTIMATE2014', 'POPESTIMATE2019')
partial.show(5) # showing first five row entries

In [10]:
us_pop = partial.relabeled(2, '2014').relabeled(3, '2019')
us_pop.show()

In [15]:
us_pop_2015 = us_pop.drop('2019') # .drop function doesn't permanently delete a column
# if we wanted to save this drop, what would we have to do?

us_pop_2015.num_columns
us_pop_2015

SEX  | AGE  | 2014
0    | 0    | 3954787
0    | 1    | 3948891
0    | 2    | 3958711
0    | 3    | 4005928
0    | 4    | 4004032
0    | 5    | 4004576
0    | 6    | 4133372
0    | 7    | 4152666
0    | 8    | 4118349
0    | 9    | 4106068
... (296 rows omitted)

_____

#### Discussion [1 min]
- What can you determine about the `SEX` column based off of this table?
    - Is `SEX` meant to be taken numerically or categorically?
    - What might each of the values of `SEX` indiciate?

In [16]:
us_pop.where('AGE',18)

SEX  | AGE  | 2014    | 2019
0    | 18   | 4221344 | 4255827
1    | 18   | 2162067 | 2172385
2    | 18   | 2059277 | 2083442

In [17]:
us_pop.where('SEX',0)

SEX  | AGE  | 2014    | 2019
0    | 0    | 3954787 | 3783052
0    | 1    | 3948891 | 3829599
0    | 2    | 3958711 | 3922044
0    | 3    | 4005928 | 3998665
0    | 4    | 4004032 | 4043323
0    | 5    | 4004576 | 4028281
0    | 6    | 4133372 | 4017227
0    | 7    | 4152666 | 4022319
0    | 8    | 4118349 | 4066194
0    | 9    | 4106068 | 4061874
... (92 rows omitted)

#### Discussion [1 min]
- What other conclusions can you learn about the way the data are recorded from these outputs? There are *two* things I notice that are interesting!!

In [18]:
us_pop.where('AGE',999) 
# age = 999, this is the combination of all ages of a given sex for that year

SEX  | AGE  | 2014      | 2019
0    | 999  | 318301008 | 328239523
1    | 999  | 156654424 | 161657324
2    | 999  | 161646584 | 166582199

In [20]:
us_pop.where('SEX',0).sort('AGE', descending=True).show(7)
# what's going on with our 100 year olds?, there are close to double the amount of 100 years old vs 99 year olds in 2014 and 2019
# what could be happening here?
# age = 100 is representing 100, 101, 102, 103, etc.
# this accounts for the largest population, compared to 99 year olds

### Summarizing our data: 2019 sex ratios

**Task**: Determine the ratio of women to men among each age group in the year 2019. Display your results effectively.

In [ ]:
us_pop_2019 = us_pop.drop('2014')
us_pop_2019.show(3)

In [ ]:
females_all_rows = us_pop_2019.where('SEX', are.equal_to(2))
females = females_all_rows.where('AGE', are.not_equal_to(999))
females.show(3)

In [ ]:
males_all_rows = us_pop_2019.where('SEX', are.equal_to(1))
males = males_all_rows.where('AGE', are.not_equal_to(999))
males.show(3)

In [ ]:
f_to_m_ratios = females.column('2019') / males.column('2019')

ratios = Table().with_columns(
    'Age', females.column('AGE'),
    'F:M Ratio', f_to_m_ratios
)

ratios.show(6)

In [ ]:
ratios.sort('Age', descending=True).show(5)

### Data visualization: line plot

In [ ]:
ratios.plot('Age', 'F:M Ratio')

## Review

In [ ]:
nba = Table.read_table('nba_salaries.csv')
nba.show(6)

**Discussion Question 1**:
- Write a code expression which contains the proportion of all salaries greater than $15M.

**Discussion Question 2:**
- What does the final block of these three blocks of code print out?

In [ ]:
department = make_array("Stat", "Stat", "Stat", "Stat", "Data","Data", "Data")
classes = make_array("20", "20", "C131A", "20", "C8","C8" , "C8" )

career = Table().with_columns("Semester", np.arange(start=1, stop=7),
                     "Dept", department,
                    "Class", classes)

In [ ]:
career.drop('Semester').where('Dept', 'Data')

In [ ]:
career.num_rows*career.num_columns